### ISSUE TITLE
There is no Histogram Module.

### ISSUE THREAD

**Issue by lyuxianqiang** [MohitLamba94/L3Fnet#1]
Thanks for sharing the source codes.
There is no Histogram Module described in the paper.  Is the Histogram module just a preprocessing step?

**Comment by MohitLamba94** [comment]
The histogram module was used only for the L3F-wild dataset as clearly specified in the paper. Yes its only a pr-processing step.

**Comment by lyuxianqiang** [comment]
Thanks for your reply.
In the 'L3Fnet for LF captured in Wild' part, you need to 'jointly train L3Fnet and Histogram Module'. Can you show the jointly training process in the code? Or maybe this process is missed in the released Github repository. 
Please check it.
Thanks.
